### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [JR-Montes/ProyectoFinalBioinf2017-II#1]
OK.

Se ve súper, quizá no te de tiempo de hacerlo todo, está bien, sólo acota en cuanto puedas para no dejar cachos a medias.

Ojo con las cursivas en nombres científicos, te faltaron.

**Comment by AzaleaGuerra** [comment]
¡Suena muy padre! No olvides que la idea es que usen lo que hemos aprendido en clase, así trata de correr los análisis desde terminal y/o R.

**Comment by JR-Montes** [comment]
OK
