### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [JR-Montes/ProyectoFinalBioinf2017-II#2]
:) 

Súper bien, felicidades.

Nota sobre los nombres de tus muestras (e.g. "cemb04s1"). Si tienes más de 9 semillas tendrás muestras que terminen en s1 y otras en s10, s21 y así. Esto puede complicarte la vida downstream porque ls te ordenará las muestras s1, s10, s11, s2, s3 ... y porque será más difícil utilizar grep y símiles para extraer una parte de tus datos. No es necesario que lo cambies ahora, pero un tip para el futuro es que consideres cuántos dígitos tendrás tus muestras y pongas ceros a la izquierda (lo que demuestra que ser un cero a la izquierda no siempre es un insulto). Por ejemplo s01, s02... s09, s10, s11

**Comment by JR-Montes** [comment]
Ha ha ha ha. Super bien el chiste! Gracias por tus comentarios. Respecto al nombre de las muestras no habrá problema pues no en todas las muestras se utilizó semilla. La gran mayoría de las muestras procesadas fueron de acículas. Incluimos un par de muestras con semillas pero de diferentes especie sólo para tener una referencia haploide para la detección de parálogos. No contamos con muestras que contengan en serie el número de las semillas.  De cualquier forma, me parece muy importante la estrategia para evitar problemas si fuera mi caso. Tomaré en cuenta el comentario para futuros trabajos.
