### ISSUE TITLE
comentarios avances 3

### ISSUE THREAD

**Issue by AliciaMstt** [JR-Montes/ProyectoFinalBioinf2017-II#3]
Se ve muy bonito y sorganizado tu proyecto, pero no me queda claro si el README es un readme o ya tu proyecto en formato md. Acuérdate que les pedí dos cosas por separado y el README es algo más sencillo para saber cómo navegar el proyecto y archivos.

**Comment by JR-Montes** [comment]
¡Hola Alicia!

Agradezco tus comentarios. ¡Es verdad! Parece que sí generé confusión. Justo hace unos minutos, acabo de hacer cambios en tu branch-master. El archivo que viste en un principio (README) y del cual me estás preguntando, efectivamente son mis avances del proyecto y ahora lo guardé como Avance_3. Escribí éste archivo a manera de ruta de trabajo y separando el pre-procesamiento del procesamiento. Incluí imágenes sobre los resultados, no todas pero si incluí. Ahora bien, escribí otro archivo llamado "README" y ahí describo la información contenida, los script de shell,  R y los requisitos para realizar el proyecto. Espero no generar más confusión. ¡Te ofrezco mil disculpas!
